# Starter pipeline
trigger:
- main

pool:
  name: Default

- task: Docker@2
  inputs:
    containerRegistry: 'ACR-AzureDevOps'
    repository: 'tetris-game-app'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



