apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris-game-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tetris-game
  template:
    metadata:
      labels:
        app: tetris-game
    spec:
      containers:
        - name: tetris-game
          image: mylabacr23.azurecr.io/tetrisgameapp:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          
---
apiVersion: v1
kind: Service
metadata:
  name: tetris-game-service
  labels:
    app: tetris-game 
spec:
  selector:
    app: tetris-game

  ports:
    - port: 80
      targetPort: 80

  type: LoadBalancer
